name: mechine_test_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  http: ^1.2.1
  fpdart: ^1.1.0
  get_it: ^7.7.0
  cloud_firestore: ^5.0.0
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.14
  internet_connection_checker_plus: ^2.4.2
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
